# Generated by Django 5.0.4 on 2026-04-09 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTutoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='ContenidoTema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuerpo_html', models.TextField(help_text='Contenido educativo en formato HTML')),
                ('material_pdf', models.FileField(blank=True, null=True, upload_to='material_temas/')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('tema', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contenido', to='AppTutoria.tema')),
            ],
        ),
    ]
