# Generated by Django 5.0.4 on 2026-04-10 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTutoria', '0002_tema_slug_contenidotema'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('archivo_video', models.FileField(help_text='Archivo de video (MP4 preferible)', upload_to='videos_temas/')),
                ('miniatura', models.ImageField(blank=True, help_text='Imagen de previsualización', null=True, upload_to='videos_thumbnails/')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción breve del video', null=True)),
                ('duracion', models.CharField(blank=True, help_text='Ej: 5:30 min', max_length=20, null=True)),
                ('orden', models.PositiveIntegerField(default=1, help_text='Orden de visualización')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='AppTutoria.tema')),
            ],
            options={
                'ordering': ['orden', 'fecha_creacion'],
            },
        ),
    ]
