# Generated by Django 5.0.4 on 2026-04-10 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTutoria', '0003_videotema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualizacionVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contador', models.PositiveIntegerField(default=0)),
                ('fecha_primera_vista', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_vista', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizaciones_videos', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vistas', to='AppTutoria.videotema')),
            ],
            options={
                'verbose_name': 'Visualización de Video',
                'verbose_name_plural': 'Visualizaciones de Videos',
                'unique_together': {('usuario', 'video')},
            },
        ),
    ]
