# Generated by Django 5.0.4 on 2026-04-11 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTutoria', '0004_visualizacionvideo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgresoEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_actividad', models.CharField(choices=[('Ejercicio', 'Ejercicio'), ('Video', 'Video'), ('Teoría', 'Teoría'), ('Examen', 'Examen')], max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('grado', models.CharField(max_length=10)),
                ('seccion', models.CharField(max_length=10)),
                ('referencia_id', models.PositiveIntegerField(blank=True, help_text='ID de la actividad específica (ejercicio, video, etc.)', null=True)),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos_estudiantes', to='AppTutoria.tema')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progreso del Estudiante',
                'verbose_name_plural': 'Progresos de los Estudiantes',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
