# Generated by Django 5.0.4 on 2026-04-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTutoria', '0005_progresoestudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='videotema',
            name='url_miniatura',
            field=models.URLField(blank=True, help_text='URL de miniatura externa (YouTube)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='videotema',
            name='url_video',
            field=models.URLField(blank=True, help_text='URL de video externo (YouTube)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='videotema',
            name='archivo_video',
            field=models.FileField(blank=True, help_text='Archivo de video (MP4 preferible)', null=True, upload_to='videos_temas/'),
        ),
        migrations.AlterField(
            model_name='videotema',
            name='miniatura',
            field=models.ImageField(blank=True, help_text='Imagen de previsualización local', null=True, upload_to='videos_thumbnails/'),
        ),
    ]
