# Generated by Django 5.0.4 on 2026-04-14 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTutoria', '0006_videotema_url_miniatura_videotema_url_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videotema',
            name='es_activo',
            field=models.BooleanField(default=True, help_text='Indica si el video está activo en el catálogo'),
        ),
    ]
