# Generated by Django 5.0.4 on 2026-04-17 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTutoria', '0007_videotema_es_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenContenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='teoria_imagenes/')),
                ('orden', models.PositiveIntegerField(default=1, help_text='Orden de aparición en el carrusel')),
                ('descripcion_alt', models.CharField(blank=True, help_text='Descripción para accesibilidad', max_length=200, null=True)),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='AppTutoria.contenidotema')),
            ],
            options={
                'verbose_name': 'Imagen de Teoría',
                'verbose_name_plural': 'Imágenes de Teoría',
                'ordering': ['orden'],
            },
        ),
    ]
