# Generated by Django 5.0.4 on 2026-04-17 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTutoria', '0008_imagencontenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresoestudiante',
            name='porcentaje_completado',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de avance en la actividad (0-100)', max_digits=5),
        ),
    ]
