# Generated by Django 5.0.4 on 2026-06-21 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTutoria', '0009_progresoestudiante_porcentaje_completado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresoestudiante',
            name='tipo_actividad',
            field=models.CharField(choices=[('Ejercicio', 'Ejercicio'), ('Video', 'Video'), ('Teoría', 'Teoría'), ('Examen Diagnóstico', 'Examen Diagnóstico'), ('Examen Temático', 'Examen Temático')], max_length=20),
        ),
    ]
