# Generated by Django 5.0.4 on 2026-04-10 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGestionUsuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nivel_dificultad_actual',
            field=models.CharField(choices=[('Básico', 'Básico'), ('Intermedio', 'Intermedio'), ('Avanzado', 'Avanzado')], default='Básico', help_text='Nivel de dificultad asignado automáticamente por el sistema', max_length=20),
        ),
    ]
