# Generated by Django 5.0.4 on 2026-04-12 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGestionUsuario', '0002_profile_nivel_dificultad_actual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricasEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precision_general', models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de aciertos global', max_digits=5)),
                ('rendimiento_academico', models.DecimalField(decimal_places=2, default=0.0, help_text='Promedio de puntajes', max_digits=5)),
                ('tiempo_respuesta_promedio', models.DecimalField(decimal_places=2, default=0.0, help_text='Tiempo medio de resoluciÃ³n en segundos', max_digits=10)),
                ('dominio_por_tema', models.JSONField(default=dict, help_text='Nivel de acierto por categorÃ\xada de geometrÃ\xada')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metricas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
