# Generated by Django 5.0.4 on 2026-04-13 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGestionUsuario', '0003_metricasestudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='puntos_acumulados',
            field=models.PositiveIntegerField(default=0, help_text='Puntos de experiencia acumulados por el estudiante'),
        ),
    ]
