# Generated by Django 5.0.4 on 2026-04-13 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGestionUsuario', '0004_profile_puntos_acumulados'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nivel_estudiante',
            field=models.PositiveIntegerField(default=1, help_text='Nivel de progresión del estudiante basado en XP'),
        ),
    ]
