# Generated by Django 5.0.4 on 2026-04-13 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGestionUsuario', '0005_profile_nivel_estudiante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insignia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
                ('icono_clase', models.CharField(help_text='Clase de FontAwesome o icono visual', max_length=50)),
                ('tipo_regla', models.CharField(choices=[('HITOS', 'Hitos de Actividad'), ('DOMINIO', 'Dominio de Tema'), ('CONSTANCIA', 'Constancia/Racha'), ('PROGRESION', 'Progresión de Nivel')], max_length=20)),
                ('valor_requerido', models.IntegerField(default=1, help_text='Valor numérico para cumplir la regla (ej: 100 puntos, 5 ejercicios)')),
            ],
        ),
        migrations.CreateModel(
            name='LogroEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_obtencion', models.DateTimeField(auto_now_add=True)),
                ('insignia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppGestionUsuario.insignia')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logros', to='AppGestionUsuario.profile')),
            ],
            options={
                'verbose_name_plural': 'Logros de Estudiantes',
                'unique_together': {('perfil', 'insignia')},
            },
        ),
    ]
