# Generated by Django 5.0.4 on 2026-04-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGestionUsuario', '0007_initial_badges'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sistema', models.CharField(default='Tesis STI', max_length=200)),
                ('email_contacto', models.EmailField(default='contacto@tesis-sti.com', max_length=254)),
                ('texto_footer', models.TextField(blank=True, default='© 2026 Tesis STI - Inteligencia en Geometría', null=True)),
            ],
            options={
                'verbose_name': 'Configuración Global',
                'verbose_name_plural': 'Configuraciones Globales',
            },
        ),
        migrations.CreateModel(
            name='PaginaEstatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('contenido_html', models.TextField(blank=True, null=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Página Estática',
                'verbose_name_plural': 'Páginas Estáticas',
            },
        ),
    ]
