# Generated by Django 5.0.4 on 2026-06-20 14:27

from django.db import migrations, models

def actualizar_correo_contacto(apps, schema_editor):
    ConfiguracionGlobal = apps.get_model('AppGestionUsuario', 'ConfiguracionGlobal')
    # Actualizar cualquier configuración global existente a luisugaz@gmail.com
    ConfiguracionGlobal.objects.all().update(email_contacto='luisugaz@gmail.com')

class Migration(migrations.Migration):

    dependencies = [
        ('AppGestionUsuario', '0008_configuracionglobal_paginaestatica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionglobal',
            name='email_contacto',
            field=models.EmailField(default='luisugaz@gmail.com', max_length=254),
        ),
        migrations.RunPython(actualizar_correo_contacto),
    ]
