# Generated by Django 5.0.4 on 2026-04-10 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEvaluar', '0003_recomendacionestudiante'),
        ('AppTutoria', '0004_visualizacionvideo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='ejercicios_imagenes/')),
                ('dificultad', models.CharField(choices=[('Básico', 'Básico'), ('Intermedio', 'Intermedio'), ('Avanzado', 'Avanzado')], default='Básico', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='AppTutoria.tema')),
            ],
        ),
        migrations.CreateModel(
            name='OpcionEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
                ('es_correcta', models.BooleanField(default=False)),
                ('retroalimentacion', models.TextField(blank=True, help_text='Mensaje que se muestra al estudiante tras elegir esta opción', null=True)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='AppEvaluar.ejercicio')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_correcto', models.BooleanField()),
                ('fecha_resolucion', models.DateTimeField(auto_now_add=True)),
                ('tiempo_empleado', models.IntegerField(help_text='Tiempo en segundos')),
                ('feedback_mostrado', models.TextField()),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppEvaluar.ejercicio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_ejercicios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
