# Generated by Django 5.0.4 on 2026-04-11 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEvaluar', '0004_ejercicio_opcionejercicio_resultadoejercicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='explicacion_tecnica',
            field=models.TextField(blank=True, help_text='Explicación teórica general del ejercicio', null=True),
        ),
    ]
