# Generated by Django 5.0.4 on 2026-04-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEvaluar', '0005_ejercicio_explicacion_tecnica'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='es_activo',
            field=models.BooleanField(default=True, help_text='Indica si el ejercicio está disponible para práctica'),
        ),
    ]
