# Generated by Django 5.0.4 on 2026-04-13 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEvaluar', '0006_ejercicio_es_activo'),
        ('AppTutoria', '0005_progresoestudiante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='categoria',
        ),
        migrations.AddField(
            model_name='pregunta',
            name='dificultad',
            field=models.CharField(choices=[('Básico', 'Básico'), ('Intermedio', 'Intermedio'), ('Avanzado', 'Avanzado')], default='Básico', max_length=20),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='tema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preguntas_diagnostico', to='AppTutoria.tema'),
        ),
    ]
