# Generated by Django 5.0.4 on 2026-04-15 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEvaluar', '0007_remove_pregunta_categoria_pregunta_dificultad_and_more'),
        ('AppTutoria', '0007_videotema_es_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='examen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='AppEvaluar.examendiagnostico'),
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('cantidad_preguntas', models.IntegerField()),
                ('tiempo_limite', models.IntegerField(help_text='Tiempo límite en minutos')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='AppTutoria.tema')),
            ],
        ),
        migrations.AddField(
            model_name='pregunta',
            name='examen_tema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preguntas', to='AppEvaluar.examen'),
        ),
    ]
