# Generated by Django 5.0.4 on 2026-04-15 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEvaluar', '0008_alter_pregunta_examen_examen_pregunta_examen_tema'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='preguntas_imagenes/'),
        ),
    ]
