# Generated by Django 5.0.4 on 2026-04-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEvaluar', '0009_pregunta_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestausuario',
            name='tiempo_respuesta',
            field=models.FloatField(blank=True, help_text='Tiempo en segundos', null=True),
        ),
    ]
