# Generated by Django 5.0.4 on 2026-04-21 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEvaluar', '0010_respuestausuario_tiempo_respuesta'),
        ('AppTutoria', '0009_progresoestudiante_porcentaje_completado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntrenamientoSVM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_promedio', models.FloatField()),
                ('nivel_estudiante', models.IntegerField(help_text='1: Básico, 2: Intermedio, 3: Avanzado')),
                ('puntos_acumulados', models.FloatField()),
                ('fue_exito', models.BooleanField(blank=True, null=True)),
                ('fecha_recomendacion', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tema_elegido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppTutoria.tema')),
            ],
        ),
    ]
