# Generated by Django 5.0.4 on 2026-04-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEvaluar', '0011_logentrenamientosvm'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='es_interactiva',
            field=models.BooleanField(default=False, help_text='Indica si el ejercicio incluye un plano interactivo'),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='meta_geometria',
            field=models.JSONField(blank=True, help_text='Configuración y objetivos para ejercicios interactivos', null=True),
        ),
    ]
