# Generated by Django 5.0.4 on 2026-04-23 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEvaluar', '0012_ejercicio_es_interactiva_ejercicio_meta_geometria'),
        ('AppTutoria', '0009_progresoestudiante_porcentaje_completado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RepasoProgramado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_proximo_repaso', models.DateTimeField()),
                ('intervalo', models.IntegerField(default=1, help_text='Intervalo actual en días')),
                ('factor_facilidad', models.FloatField(default=2.5, help_text='Factor de facilidad (EF) del algoritmo SM-2')),
                ('estado', models.BooleanField(default=True, help_text='Indica si el repaso está activo')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repasos', to=settings.AUTH_USER_MODEL)),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repasos_programados', to='AppTutoria.tema')),
            ],
            options={
                'verbose_name': 'Repaso Programado',
                'verbose_name_plural': 'Repasados Programados',
                'unique_together': {('estudiante', 'tema')},
            },
        ),
    ]
