# Generated by Django 5.0.4 on 2026-05-04 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEvaluar', '0014_remove_pregunta_examen_tema_and_more'),
        ('AppTutoria', '0009_progresoestudiante_porcentaje_completado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlPracticaTema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examen_desbloqueado', models.BooleanField(default=False, help_text='Indica si el primer examen del tema ha sido desbloqueado')),
                ('ultima_practica_finalizada', models.DateTimeField(blank=True, help_text='Fecha y hora de la última vez que terminó una sesión de 20 ejercicios', null=True)),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppTutoria.tema')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles_practica', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Control de Práctica',
                'verbose_name_plural': 'Controles de Práctica',
                'unique_together': {('usuario', 'tema')},
            },
        ),
    ]
