# Generated by Django 5.0.4 on 2026-06-19 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEvaluar', '0015_controlpracticatema'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestausuario',
            name='feedback_ia',
            field=models.TextField(blank=True, help_text='Retroalimentación pedagógica generada por la IA', null=True),
        ),
    ]
