# Generated by Django 5.0.4 on 2026-06-21 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEvaluar', '0016_respuestausuario_feedback_ia'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcion',
            name='retroalimentacion',
            field=models.TextField(blank=True, help_text='Mensaje que se muestra al estudiante tras elegir esta opción', null=True),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='explicacion_tecnica',
            field=models.TextField(blank=True, help_text='Explicación teórica general de la pregunta', null=True),
        ),
    ]
